<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AMILTPBLR364" ignored="0" name="Regression_test" tests="4" failures="1" timestamp="14 May 2018 09:47:37 GMT" time="4.047" errors="0">
  <testcase name="Supertest" time="4.014" classname="testpackage.Day2">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testpackage.Day2.Supertest() didn&amp;apos;t finish within the time-out 4000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testpackage.Day2.Supertest() didn't finish within the time-out 4000
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 2 stack frames]]>
    </failure>
  </testcase> <!-- Supertest -->
  <testcase name="Supertest2" time="0.001" classname="testpackage.Day2"/>
  <testcase name="Supertest3" time="0.002" classname="testpackage.Day2"/>
  <testcase name="atest3" time="0.0" classname="testpackage.Day2">
    <skipped/>
  </testcase> <!-- atest3 -->
</testsuite> <!-- Regression_test -->
