<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="AMILTPBLR364" name="testpackage.Day2" tests="4" failures="0" timestamp="14 May 2018 09:47:37 GMT" time="4.017" errors="1">
  <testcase name="Supertest3" time="0.002" classname="testpackage.Day2"/>
  <testcase name="atest3" time="0.000" classname="testpackage.Day2">
    <skipped/>
  </testcase> <!-- atest3 -->
  <testcase name="Supertest2" time="0.001" classname="testpackage.Day2"/>
  <testcase name="Supertest" time="4.014" classname="testpackage.Day2">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method testpackage.Day2.Supertest() didn&#039;t finish within the time-out 4000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testpackage.Day2.Supertest() didn't finish within the time-out 4000
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:69)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Supertest -->
</testsuite> <!-- testpackage.Day2 -->
